import Head from "next/head";
import { Clock } from "../components/Layout/Clock";
import { Timer } from "../components/Layout/Timer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Clock App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Clock /> */}
      <Timer />
    </>
  );
}
